# Generated by Django 4.1.2 on 2023-12-12 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="storedfile",
            options={
                "ordering": ["name"],
                "verbose_name": "Stored File",
                "verbose_name_plural": "Stored Files",
            },
        ),
        migrations.AddField(
            model_name="storedfile",
            name="name",
            field=models.CharField(default="", max_length=512, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="link",
            name="href",
            field=models.CharField(
                default="9W5q6E6xZP6WwaLyj5uDKQ",
                editable=False,
                max_length=16,
                unique=True,
                verbose_name="Href",
            ),
        ),
    ]
