# Generated by Django 4.1.2 on 2023-12-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0003_alter_storedfile_options_storedfile_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="href",
            field=models.CharField(
                default="MieSX8ziwU4Fwvoz",
                editable=False,
                max_length=16,
                unique=True,
                verbose_name="Href",
            ),
        ),
    ]
